version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: ec2-user

#@destination
# source에서 지정된 파일을 받을 위치
# 이후 jar를 실행하는등은 destination에서 옮긴 파일들로 진행된다.

#@Permission
# codedeploy에서 ec2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 한다

#hooks
# codedeploy 배포 단계에서 실행할 명령어를 지정한다.
# APplicationSTart라는 단계에서 deploy.sh를 ec2-user 권한으로 실행하게 한다.
# timeout: 60 으로 줘서 무한정 기다리지 않게 한다.